// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReportPKKMasterDataLapangan struct {
	ID            int32              `json:"id"`
	NamaLapangan  string             `json:"nama_lapangan"`
	HargaLapangan pgtype.Numeric     `json:"harga_lapangan"`
	HargaBallboy  pgtype.Numeric     `json:"harga_ballboy"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ReportPKKMasterDataReclub struct {
	ID              int32              `json:"id"`
	JadwalAtauHari  string             `json:"jadwal_atau_hari"`
	TotalLamaJadwal pgtype.Numeric     `json:"total_lama_jadwal"`
	BiayaDaftar     pgtype.Numeric     `json:"biaya_daftar"`
	BiayaPerJam     pgtype.Numeric     `json:"biaya_per_jam"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ReportPKKReportKeuangan struct {
	ID          int32              `json:"id"`
	Tanggal     pgtype.Date        `json:"tanggal"`
	KasIn       pgtype.Numeric     `json:"kas_in"`
	KasOut      pgtype.Numeric     `json:"kas_out"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
