// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
)

type Querier interface {
	CreateReportKeuangan(ctx context.Context, arg CreateReportKeuanganParams) (ReportPKKReportKeuangan, error)
	DeleteReportKeuangan(ctx context.Context, id int32) error
	GetReportKeuangan(ctx context.Context) ([]ReportPKKReportKeuangan, error)
	GetReportKeuanganByID(ctx context.Context, id int32) (ReportPKKReportKeuangan, error)
	UpdateReportKeuangan(ctx context.Context, arg UpdateReportKeuanganParams) (ReportPKKReportKeuangan, error)
}

var _ Querier = (*Queries)(nil)
