// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReportKeuangan = `-- name: CreateReportKeuangan :one
INSERT INTO "reportPKK"."ReportKeuangan" (
    tanggal, kas_in, kas_out, description
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, tanggal, kas_in, kas_out, description, created_at, updated_at
`

type CreateReportKeuanganParams struct {
	Tanggal     pgtype.Date    `json:"tanggal"`
	KasIn       pgtype.Numeric `json:"kas_in"`
	KasOut      pgtype.Numeric `json:"kas_out"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateReportKeuangan(ctx context.Context, arg CreateReportKeuanganParams) (ReportPKKReportKeuangan, error) {
	row := q.db.QueryRow(ctx, createReportKeuangan,
		arg.Tanggal,
		arg.KasIn,
		arg.KasOut,
		arg.Description,
	)
	var i ReportPKKReportKeuangan
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.KasIn,
		&i.KasOut,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReportKeuangan = `-- name: DeleteReportKeuangan :exec
DELETE FROM "reportPKK"."ReportKeuangan"
WHERE id = $1
`

func (q *Queries) DeleteReportKeuangan(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReportKeuangan, id)
	return err
}

const getReportKeuangan = `-- name: GetReportKeuangan :many
SELECT id, tanggal, kas_in, kas_out, description, created_at, updated_at FROM "reportPKK"."ReportKeuangan"
ORDER BY tanggal DESC
`

func (q *Queries) GetReportKeuangan(ctx context.Context) ([]ReportPKKReportKeuangan, error) {
	rows, err := q.db.Query(ctx, getReportKeuangan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportPKKReportKeuangan
	for rows.Next() {
		var i ReportPKKReportKeuangan
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.KasIn,
			&i.KasOut,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportKeuanganByID = `-- name: GetReportKeuanganByID :one
SELECT id, tanggal, kas_in, kas_out, description, created_at, updated_at FROM "reportPKK"."ReportKeuangan"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReportKeuanganByID(ctx context.Context, id int32) (ReportPKKReportKeuangan, error) {
	row := q.db.QueryRow(ctx, getReportKeuanganByID, id)
	var i ReportPKKReportKeuangan
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.KasIn,
		&i.KasOut,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReportKeuangan = `-- name: UpdateReportKeuangan :one
UPDATE "reportPKK"."ReportKeuangan"
SET 
    tanggal = $2,
    kas_in = $3,
    kas_out = $4,
    description = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tanggal, kas_in, kas_out, description, created_at, updated_at
`

type UpdateReportKeuanganParams struct {
	ID          int32          `json:"id"`
	Tanggal     pgtype.Date    `json:"tanggal"`
	KasIn       pgtype.Numeric `json:"kas_in"`
	KasOut      pgtype.Numeric `json:"kas_out"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) UpdateReportKeuangan(ctx context.Context, arg UpdateReportKeuanganParams) (ReportPKKReportKeuangan, error) {
	row := q.db.QueryRow(ctx, updateReportKeuangan,
		arg.ID,
		arg.Tanggal,
		arg.KasIn,
		arg.KasOut,
		arg.Description,
	)
	var i ReportPKKReportKeuangan
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.KasIn,
		&i.KasOut,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
